version: '3.8'

services:
  nginx:
    image: nginx:1.17.6
    container_name: nginx
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./services/web/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
  web:
    build: ./services/web

    command: gunicorn -k gevent -w 1 --bind 0.0.0.0:3000 manage:app
    container_name: web
    volumes:
      - ./services/web/:/usr/src/app/
    expose:
      - "3000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    logging:
        driver: "json-file"
        options:
          max-size: "10m"  # Limit log file size
          max-file: "3"
  db:
    image: postgres:13
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=alphabet
      - POSTGRES_PASSWORD=alphabet
      - POSTGRES_DB=alphabet_prod

  redis:
       image: redis:6.2-alpine
       container_name: redis
       ports:
         - '6379:6379'

volumes:
  postgres_data:
